name: Satsails
description: "Sail your wealth to the cloud!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  http: ^1.2.1
  local_auth: ^2.1.8
  hive: ^2.2.3
  webview_flutter: ^4.5.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
#  ai_barcode_scanner 3.4.3 for web compil
  fl_chart: ^0.66.2
  bip39: ^1.0.6
  flutter_riverpod: ^2.5.1
#  Need windows linux and web compils
  bdk_flutter: ^0.31.2-dev.1
  flutter_i18n: ^0.35.1
#  need windows linux ios and mac and web compils
  boltz_dart:
    git:
      url: https://github.com/SatoshiPortal/boltz-dart.git
      ref: trunk
  lwk_dart:
    git:
      url: https://github.com/SatoshiPortal/lwk-dart.git
      ref: trunk
  forex_currency_conversion: ^0.9.1
  icons_plus: ^5.0.0
  loading_animation_widget: ^1.2.1
  group_button: ^5.3.4
  responsive_framework: ^1.4.0
  liquid_pull_to_refresh: ^3.0.1
  bolt11_decoder: ^1.0.2
  action_slider: ^0.7.0
  hooks_riverpod: ^2.5.1
  interactive_slider: ^0.2.1
  fluttertoast: ^8.2.5
#  flutter_styled_toast: ^2.2.1 use to compil toas everywhere
  flutter_card_swiper: ^7.0.0
  calendar_date_picker2: ^0.5.6
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.2.6
  i18n_extension: ^12.0.1

  path_provider: any
  flutter_hooks: any
  decimal: any
  web_socket_channel: any
dev_dependencies:
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - lib/assets/satsails.png

#compil incons to all envs
flutter_launcher_icons:
  android: true
  image_path: "lib/assets/satsails.png"
flutter_native_splash:
    color: "#FFFFFF"
    image: "lib/assets/satsails.png"
    android: true
    ios: true
    web: true